version: "2"

run:
  concurrency: 8
  timeout: 5m
  issues-exit-code: 1
  tests: false
  go: ""

  
linters:
  default: standard
  enable:
    - govet
    - staticcheck
    - ineffassign
    - unparam
    - nakedret
    - errorlint
    - dupl
    - misspell
    - prealloc
    - bodyclose # Checks if http.Response.Body is closed.
    - gochecknoglobals # Prohibits global variables.
    - gocritic # The most opinionated linter, can be noisy.
    - gosec # Security linter. Highly recommended for production services.
    - lll # Line length linter.
    - funlen # Function length linter.
    - cyclop # Cyclomatic complexity.
